import type {Metadata} from "next";
import localFont from "next/font/local";
import "./globals.css";
import React from "react";
import MobileOnly from "@/components/molecules/MobileOnly";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next Mobile",
  description: "Generated by create next mobile",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <>
        <div className="block md:hidden">
        {children}
        </div>

        <div className="hidden md:flex h-[100vh] justify-center items-center bg-gray-100 text-center">
           <MobileOnly/>
        </div>
      </>
      </body>
    </html>
  );
}
